version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      scientifique:
        patterns: ["numpy", "scipy", "pandas", "statsmodels", "scikit-learn", "matplotlib", "lifelines"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
